# Generated by Django 5.0.7 on 2026-05-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("branch_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Branches",
                "db_table": "branch",
                "ordering": ["branch_name"],
            },
        ),
        migrations.CreateModel(
            name="Drive",
            fields=[
                ("drive_id", models.AutoField(primary_key=True, serialize=False)),
                ("drive_name", models.CharField(max_length=200)),
                ("drive_year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="inactive",
                        max_length=10,
                    ),
                ),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True, related_name="drives", to="portal.branch"
                    ),
                ),
            ],
            options={
                "db_table": "drive",
                "ordering": ["-drive_year", "drive_name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("cmp_id", models.AutoField(primary_key=True, serialize=False)),
                ("cmp_name", models.CharField(max_length=200)),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to="portal.drive",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "company",
                "ordering": ["cmp_name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("profile_name", models.CharField(max_length=200)),
                ("ctc", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cmp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="portal.company",
                    ),
                ),
            ],
            options={
                "db_table": "profile",
                "ordering": ["profile_name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("std_id", models.AutoField(primary_key=True, serialize=False)),
                ("std_name", models.CharField(max_length=200)),
                ("cpi", models.DecimalField(decimal_places=2, max_digits=4)),
                ("placed", models.BooleanField(default=False)),
                ("switch_app", models.BooleanField(default=False)),
                ("cmp_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ctc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="portal.branch",
                    ),
                ),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="portal.drive",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="portal.profile",
                    ),
                ),
            ],
            options={
                "db_table": "student",
                "ordering": ["std_name"],
            },
        ),
    ]
