# Generated by Django 5.0.7 on 2026-05-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="cmp_name",
        ),
        migrations.AddField(
            model_name="student",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hired_students",
                to="portal.company",
            ),
        ),
    ]
