# Generated by Django 5.0.7 on 2026-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_remove_student_cmp_name_student_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="std_id",
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                default="TEMP", max_length=50, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
