# Generated by Django 5.0.7 on 2026-05-12 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_remove_student_std_id_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="branch_id",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Branch ID must be in the format PROGRAM_BRANCH (e.g. BTECH_CSE)",
                        regex="^[A-Z]+_[A-Z]+$",
                    )
                ],
            ),
        ),
    ]
