# Generated by Django 5.0.7 on 2026-05-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_branch_branch_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="ctc",
        ),
    ]
