# Generated by Django 5.0.7 on 2026-05-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_remove_student_ctc"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stipend",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
