# Generated by Django 5.0.7 on 2026-05-13 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_profile_stipend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drive",
            name="drive_id",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Drive ID must be in the format SI2025, PD2025 etc.",
                        regex="^[A-Z]{2}\\d{4}$",
                    )
                ],
            ),
        ),
    ]
