# Generated by Django 5.0.7 on 2026-05-13 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_alter_drive_drive_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="placed",
        ),
        migrations.AddField(
            model_name="profile",
            name="offer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WI", "Winter Internship"),
                    ("WI+J", "Winter Internship + Job"),
                    ("J", "Job"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="placement_status",
            field=models.CharField(
                choices=[
                    ("Unplaced", "Unplaced"),
                    ("Placed", "Placed"),
                    ("PPO", "PPO"),
                    ("Summer Internship", "Summer Internship"),
                ],
                default="Unplaced",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="drive",
            name="drive_id",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Drive ID must start with SI or PD followed by 4 digits (e.g. SI2025, PD2025).",
                        regex="^(SI|PD)\\d{4}$",
                    )
                ],
            ),
        ),
    ]
