# Generated by Django 5.0.7 on 2026-05-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_adminprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="offer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WI", "Winter Internship"),
                    ("WI+J", "Winter Internship + Job"),
                    ("J", "Job"),
                    ("SI", "Summer Internship"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
