# Generated by Django 6.0.5 on 2026-06-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_alter_profile_offer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="offer_letter",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
