# Generated by Django 6.0.5 on 2026-06-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_student_offer_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="branches",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="portal.branch"
            ),
        ),
    ]
