# Generated by Django 6.0.5 on 2026-06-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0012_profile_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewRound",
            fields=[
                ("round_id", models.AutoField(primary_key=True, serialize=False)),
                ("round_number", models.PositiveIntegerField()),
                ("round_name", models.CharField(max_length=200)),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("applications", "Applications"),
                            ("oa", "OA Shortlisted"),
                            ("round", "Round"),
                            ("gd", "GD Round"),
                            ("technical", "Technical Round"),
                            ("hr", "HR Round"),
                            ("results", "Results"),
                            ("custom", "Custom"),
                        ],
                        default="round",
                        max_length=20,
                    ),
                ),
                ("is_final", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="portal.profile",
                    ),
                ),
            ],
            options={
                "db_table": "interview_round",
                "ordering": ["round_number"],
                "unique_together": {("profile", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="RoundStudent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_students",
                        to="portal.interviewround",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_rounds",
                        to="portal.student",
                    ),
                ),
            ],
            options={
                "db_table": "round_student",
                "unique_together": {("round", "student")},
            },
        ),
    ]
