# Generated by Django 4.2.30 on 2026-06-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0013_interviewround_roundstudent"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewround",
            name="is_interview_shortlist",
            field=models.BooleanField(default=False),
        ),
    ]
